### ISSUE TITLE
When using online editor the preview area is broken

### ISSUE THREAD

**Issue by axl411** [eleme/mobilists#19]
<img width="1275" alt="image copied on 2017-02-09 at 19 37 pm" src="https://cloud.githubusercontent.com/assets/5897680/22781823/488bf14a-eeff-11e6-885a-e35fd0c66178.png">

The preview area always likes that. I very unhappy.

(Of course I `ctl+s`ed)

**Comment by stephenwzl** [comment]
my fault, the style sheet only support for Chrome because of Flex layout
