### ISSUE TITLE
配置google统计

### ISSUE THREAD

**Issue by axl411** [eleme/mobilists#2]

**Comment by axl411** [comment]
@BryanOne 注册好了百度统计的公司账号在这发一下然后我来配置

**Comment by axl411** [comment]
暂且配了，未确认是否有效

**Comment by BryanOne** [comment]
百度这个去掉吧，以google为准


Best Regards

Qing Wang（Bryan）Shanghai - Mobile Dev, ELEME Inc.
Email: qing.wang@ele.me <mailto:qing.wang@ele.me> | Mobile: 18101898771
http://ele.me <http://ele.me/>

**Comment by axl411** [comment]
done
