### ISSUE TITLE
README 描述流程可以优化一下

### ISSUE THREAD

**Issue by stephenwzl** [eleme/mobilists#8]
比如需要先用brew 或 配置 nvm 安装 NodeJS，
其次 npm install --save ***\* 这些命令不是必须的，在package.json里面的dependency里面列出来的依赖直接在 folder下面 npm install 一下就好了

**Comment by axl411** [comment]
just do it

**Comment by stephenwzl** [comment]
got it

**Comment by stephenwzl** [comment]
#25
